// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmCMAu0_9GX9DBF9s-xXRzM818GsarBUY',
    appId: '1:408390509656:android:7294f851f17f989732162d',
    messagingSenderId: '408390509656',
    projectId: 'itoju-7c0f0',
    storageBucket: 'itoju-7c0f0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO9Mnt-TxGO7UbJ8fMT777bHsXPpZHsiQ',
    appId: '1:408390509656:ios:a30416048839d95232162d',
    messagingSenderId: '408390509656',
    projectId: 'itoju-7c0f0',
    storageBucket: 'itoju-7c0f0.firebasestorage.app',
    androidClientId: '408390509656-okek4uhov71isbocbvko30vnkmnr9rov.apps.googleusercontent.com',
    iosClientId: '408390509656-qkpjaihr02gmlvhl7ke56k0ieql0ek8p.apps.googleusercontent.com',
    iosBundleId: 'com.itoju.app',
  );
}
